apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uaaapp
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: uaaapp
    spec:
      containers:
      - name: uaaapp-app
        image: killingbond/uaaapp
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/config
        - name: JHIPSTER_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: registry-admin-password
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/eureka/
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://uaaapp-mysql.default.svc.cluster.local:3306/uaaapp?useUnicode=true&characterEncoding=utf8&useSSL=false
        - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
          value: uaaapp-elasticsearch.default.svc.cluster.local:9300
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: uaaapp-kafka.default.svc.cluster.local
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
          value: uaaapp-zookeeper.default.svc.cluster.local
        - name: JAVA_OPTS
          value: " -Xmx256m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - name: web
          containerPort: 9999
        readinessProbe:
          httpGet:
            path: /management/health
            port: web
        livenessProbe:
          httpGet:
            path: /management/health
            port: web
          initialDelaySeconds: 180

