apiVersion: v1
kind: Service
metadata:
  name: gatewayapp
  namespace: default
  labels:
    app: gatewayapp
spec:
  selector:
    app: gatewayapp
  type: LoadBalancer
  ports:
  - name: web
    port: 8080
